#!/bin/bash

# This script pulls the latest sample configs from the EVerest repository (defaults to the main branch but can receive any ref).

set -e

BRANCH=$1
BRANCH=${BRANCH:-main}

for file in sample-configs/*; do
    file=${file##*/}
    URL="https://raw.githubusercontent.com/EVerest/everest-core/refs/heads/$BRANCH/config/$file"
    echo "Pulling $URL"

    curl -sS -o "sample-configs/$file" "$URL"
done

echo "Do you want to update the admin panel data? (this is required for updates to be reflected in the admin panel, but it requires a running everest instance)"

read -p "[Y/n]: " -r confirm

case "$confirm" in
    [Yy]* | "")
        echo "updating simulator data"
        node update-simulator-data.js
        echo "Simulator data update completed."
        ;;

    *)
        echo "Config pulling completed. Skipping admin panel data update."
        exit 0
        ;;
esac
