name: Package everest-admin-panel

on: workflow_dispatch

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Tar
        run: tar -C dist -czf everest-admin-panel.tar.gz ./
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v0.1.0
          files: everest-admin-panel.tar.gz
